### ISSUE TITLE
Odovzdanie finálnej verzie zadávateľovi.

### ISSUE THREAD

**Issue by jakub-toma** [TIS2020-FMFI/krokovy-motor#104]
prebehlo stretnutie so zadávateľom
aplikovali sme zmeny ku vyhladavaniu minim
otestovali sme celkovú funkcionalitu
zadávateľ bol spokojný s výsledným projektom
odovzdali sme mu program vo formáte jar

**Comment by jakub-toma** [comment]
priebeh stretnutia je popísaný v popise tejto issue a bude podrobne popísaný v zázname zo stretnutia #93

**Comment by pavelpetrovic** [comment]
super, hotova reportaz minuta po minute. :-)
