### ISSUE TITLE
Uprava vzhladu katalogu poziadaviek

### ISSUE THREAD

**Issue by j-mjrsk** [TIS2020-FMFI/krokovy-motor#16]
https://docs.google.com/document/d/1_8cBW3x6xfxcjxEZgmq_nBVBfYQ1V87Vm6R6Uz2ew-w/edit#

**Comment by pavelpetrovic** [comment]
preco su vsetky issue na katalog poziadaviek CLOSED, ked v branchi documentation nevidim ziaden vysledny katalog_poziadaviek.docx?

**Comment by j-mjrsk** [comment]
V branch documentation pridany vysledny katalog poziadaviek vo formate pdf ...
