### ISSUE TITLE
Trieda pre uchovanie konfiguracneho suboru

### ISSUE THREAD

**Issue by FilipSekerka** [TIS2020-FMFI/krokovy-motor#17]
Aby sme mohli ulozit konfiguracne udaje najprv  do pamate a az po skonceni merania ich zapisali do suboru.

**Comment by FilipSekerka** [comment]
Spravene, treba ale este vymysliet ako budeme kontrolovat, ze ake jednotky uhlov sa pouzivaju a na zaklade toho robit kontrolu pre rozsah.
https://github.com/TIS2020-FMFI/krokovy-motor/blob/basic_components/basic_components/measurement/ConfigurationFile.java

**Comment by MatejKomlossy** [comment]
nahradene triedou Settings
