### ISSUE TITLE
Spravit system vynimiek pre cely program

### ISSUE THREAD

**Issue by FilipSekerka** [TIS2020-FMFI/krokovy-motor#20]

**Comment by FilipSekerka** [comment]
vo vyslednom dokumente treba opravit verziu javy na javu 8 64 bit a takisto napisat, ze omni driver musi byt tiez 64 bit

**Comment by MatejKomlossy** [comment]
https://github.com/TIS2020-FMFI/krokovy-motor/tree/master/project/src/Exceptions
