### ISSUE TITLE
Struktura dokumentu navrh

### ISSUE THREAD

**Issue by j-mjrsk** [TIS2020-FMFI/krokovy-motor#22]

**Comment by j-mjrsk** [comment]
[brewster_navrh.docx](https://github.com/TIS2020-FMFI/krokovy-motor/files/5436009/brewster_navrh.docx)

**Comment by j-mjrsk** [comment]
kontrola exportu ( pages -> docx ) ...

**Comment by MatejKomlossy** [comment]
export vyzera dobre

**Comment by j-mjrsk** [comment]
https://drive.google.com/file/d/11ytsAhYdkW2qhhq4fZzvhVND6C4sy35g/view?usp=sharing
