### ISSUE TITLE
Vytvoriť jeden z dvojice UML state a UML sequence diagram

### ISSUE THREAD

**Issue by FilipSekerka** [TIS2020-FMFI/krokovy-motor#24]

**Comment by FilipSekerka** [comment]
vybrali sme si stavovy diagram

**Comment by FilipSekerka** [comment]
prva verzia state diagramu
https://drive.google.com/file/d/18pzRsyyLKXkPPYU7oeHBHSMOiyCl-1AK/view?usp=sharing

**Comment by pavelpetrovic** [comment]
moze to takto byt.
