### ISSUE TITLE
Vytvorenie UML class diagramu

### ISSUE THREAD

**Issue by FilipSekerka** [TIS2020-FMFI/krokovy-motor#25]

**Comment by FilipSekerka** [comment]
https://drive.google.com/file/d/1gjn5tua3vL-W9Hyb8Z0n1FJvCPfeTmLF/view?usp=sharing

**Comment by MatejKomlossy** [comment]
https://github.com/TIS2020-FMFI/krokovy-motor/commit/2ed92f84b948c68e6f9fc547f079d3a010a3308c#diff-d0bc923ca5476a5653e73b89a61c099e1d7be367f31bf5f3e2f7ed20a553a466

**Comment by pavelpetrovic** [comment]
veci, ktore sme este neprediskutovali, prosim nezatvarajte.
zda sa mi, ze korespodencia voci komponentnemu diagramu nie je dostatocna, je tu mozno privela zavislosti.
podla katalogu poziadaviek by malo byt viacero typov grafov, ale nevidim to tu a este par drobnosti - mali by sme to najskor prediskutovat.

**Comment by FilipSekerka** [comment]
hotovo
