### ISSUE TITLE
Špecifikácia vonkajších interfejsov

### ISSUE THREAD

**Issue by FilipSekerka** [TIS2020-FMFI/krokovy-motor#28]

**Comment by j-mjrsk** [comment]
Vypracovanie specifikacie vonkajsich interfejcov + komunikacny protokol pre zariadenie Picaxe 18M2.
https://docs.google.com/document/d/11ytsAhYdkW2qhhq4fZzvhVND6C4sy35g/edit#heading=h.2et92p0

**Comment by j-mjrsk** [comment]
specifikacia vonkajsich interfejcov dokoncena - https://docs.google.com/document/d/11ytsAhYdkW2qhhq4fZzvhVND6C4sy35g/edit#heading=h.2et92p0
