### ISSUE TITLE
Kompletny dokument navrhu

### ISSUE THREAD

**Issue by FilipSekerka** [TIS2020-FMFI/krokovy-motor#29]

**Comment by FilipSekerka** [comment]
vytvorit google drive dokument pre navrh

**Comment by FilipSekerka** [comment]
https://drive.google.com/file/d/11ytsAhYdkW2qhhq4fZzvhVND6C4sy35g/view?usp=sharing

**Comment by FilipSekerka** [comment]
https://drive.google.com/file/d/11ytsAhYdkW2qhhq4fZzvhVND6C4sy35g/view?usp=sharing

**Comment by FilipSekerka** [comment]
https://docs.google.com/document/d/11ytsAhYdkW2qhhq4fZzvhVND6C4sy35g/edit

**Comment by j-mjrsk** [comment]
https://github.com/TIS2020-FMFI/krokovy-motor/blob/documentation/Documentation/navrh_testovacie_scenare.pdf
