### ISSUE TITLE
Testovacie scenáre

### ISSUE THREAD

**Issue by jakub-toma** [TIS2020-FMFI/krokovy-motor#34]

**Comment by j-mjrsk** [comment]
1. verzia dokumentu testovacie scenare - https://docs.google.com/document/d/1KUwTYHX16TRJiDSdM9AsWhWiv7FJ7jlw/edit#

**Comment by FilipSekerka** [comment]
pridat do dokumentu navrh

**Comment by j-mjrsk** [comment]
https://github.com/TIS2020-FMFI/krokovy-motor/blob/documentation/Documentation/navrh_testovacie_scenare.pdf
