### ISSUE TITLE
average mod pri live mod

### ISSUE THREAD

**Issue by FilipSekerka** [TIS2020-FMFI/krokovy-motor#64]

**Comment by MatejKomlossy** [comment]
https://github.com/TIS2020-FMFI/krokovy-motor/pull/69

**Comment by MatejKomlossy** [comment]
poriesit v gui este

**Comment by MatejKomlossy** [comment]
> poriesit v gui este

treba aj livemod zastavit a spustit

**Comment by jakub-toma** [comment]
otestované na dnešnom stretnutí, zatváram.
