### ISSUE TITLE
Zoznam požiadaviek

### ISSUE THREAD

**Issue by MatejKomlossy** [TIS2020-FMFI/krokovy-motor#7]
Vypracovať zoznam požiadaviek na základe prepisu stretnutia so zadávateľom

**Comment by FilipSekerka** [comment]
Po dalsej komunikacii so zadavatelom sme zisitli, ze pojmom integracny cas a expozicny cas sa mysli to iste(v kniznici pre spektrometer sa to vola integracny cas).

Parametre pre lampu:
                     - ak to je wolframova halogenova lampa, tak ukladame : typ, napatie a prud + poznamka   
                     - ak to je deuteriova lampa, tak ukladame: typ + poznamka

**Comment by jakub-toma** [comment]
zoznam poziadaviek vytvoreny

**Comment by pavelpetrovic** [comment]
rozumiem tomu spravne, ze mate nejaky hruby zoznam poziadaviek a robite na katalogu poziadaviek?

**Comment by FilipSekerka** [comment]
ano, toto je len predbezny zoznam poziadaviek, budeme z neho vychadzat pri tvorbe katalogu poziadaviek
