### ISSUE TITLE
Struktura katalogu poziadaviek .

### ISSUE THREAD

**Issue by j-mjrsk** [TIS2020-FMFI/krokovy-motor#8]
Kostra katalógu

**Comment by j-mjrsk** [comment]
[katalog_poziadaviek.docx](https://github.com/TIS2020-FMFI/krokovy-motor/files/5324522/katalog_poziadaviek.docx)

**Comment by pavelpetrovic** [comment]
ten titulny list asi nepotrebujem, staci, ked tie informacie, co su na nom budu v nadpise, setrime white-space :-)
ale ak ho tam chcete mat, tak mi nevadi.

**Comment by pavelpetrovic** [comment]
mozno by sa oplatilo to zatial dat na nejaky zdielany google-drive aby ste to mohli priebezne tvorit a zdialano editovat.

**Comment by jakub-toma** [comment]
https://docs.google.com/document/d/1_8cBW3x6xfxcjxEZgmq_nBVBfYQ1V87Vm6R6Uz2ew-w/edit?usp=sharing
